fos_rest:
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
      - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
